// pnpm dev:env: points local development at the DEPLOYED dev stack. It reads the Pulumi stack outputs and
// writes api/.env.local and web/.env.local with names, IDs and URLs only.
// Never secrets: only the outputs listed below are written (an allow-list), and Pulumi prints secret
// outputs as "[secret]" without --show-secrets, which this script refuses to write. Secret VALUES are read
// from Secrets Manager at runtime. Both files are git-ignored. CONCEPT: secrets-management
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

// Step 1: the stack outputs. `pulumi stack output` reads Pulumi Cloud state; AWS_PROFILE is set for
// consistency with every other local Pulumi command.
const raw = execFileSync("pulumi", ["stack", "output", "--json", "--stack", "dev"], {
  cwd: "infra",
  env: { ...process.env, AWS_PROFILE: process.env.AWS_PROFILE ?? "ticketlite" },
  encoding: "utf8",
});
const outputs = JSON.parse(raw) as Record<string, unknown>;
if (!outputs.eventsTableName) {
  console.error("The dev stack has no outputs yet: it has not been deployed. Deploy it through CI first");
  console.error("(docs/CICD-SETUP.md), or use offline mode (pnpm dev) or mock mode (pnpm dev:mock).");
  process.exit(1);
}

// Step 2: one env line per allowed output. Missing optional outputs (flags off) are left out.
function line(name: string, output: string): string[] {
  const value = outputs[output];
  if (value === undefined || value === null || value === "") return []; // e.g. a flag is off
  if (String(value) === "[secret]") throw new Error(`Refusing to write secret output ${output}`);
  return [`${name}=${String(value)}`];
}

const generated = (purpose: string) => [
  `# Generated by \`pnpm dev:env\` from the Pulumi stack outputs (${new Date().toISOString()}). Do not edit;`,
  "# re-run the command after a deploy. Names, IDs and URLs only, never secrets. Git-ignored.",
  `# ${purpose}`,
];

// Step 3: the API talks to the deployed AWS resources with your local AWS profile.
const api = [
  ...generated("The local API (http://localhost:3000) uses the deployed dev stack's AWS resources."),
  "AWS_PROFILE=ticketlite",
  "AWS_REGION=us-east-1",
  "DYNAMODB_ENDPOINT=", // empty = real DynamoDB, not DynamoDB Local
  ...line("EVENTS_TABLE", "eventsTableName"),
  ...line("ORGANIZERS_TABLE", "organizersTableName"),
  ...line("SESSIONS_TABLE", "sessionsTableName"),
  ...line("BOOKINGS_TABLE", "bookingsTableName"),
  ...line("IDEMPOTENCY_TABLE", "idempotencyTableName"),
  ...line("USER_POOL_ID", "userPoolId"),
  ...line("USER_POOL_CLIENT_ID", "userPoolClientId"),
  ...line("COGNITO_DOMAIN_URL", "cognitoDomain"),
  ...line("BOOKING_STATE_MACHINE_ARN", "bookingStateMachineArn"),
  ...line("POSTERS_BUCKET", "postersBucketName"),
  ...line("EVENT_BUS_NAME", "eventBusName"),
  ...line("OPENSEARCH_ENDPOINT", "opensearchEndpoint"),
  `# For reference: the deployed app ${outputs.cloudFrontUrl ?? ""} and API Gateway ${outputs.apiUrl ?? ""}`,
];

// Step 4: the web app calls the LOCAL API, and AppSync directly. The AppSync API key is public by design
// (it ships in the deployed site's JavaScript too).
const web = [
  ...generated("The local web app (http://localhost:3001) uses the local API and the deployed AppSync API."),
  "NEXT_PUBLIC_API_URL=http://localhost:3000",
  ...line("NEXT_PUBLIC_APPSYNC_URL", "appsyncUrl"),
  ...line("NEXT_PUBLIC_APPSYNC_API_KEY", "appsyncApiKey"),
  `# For reference: web bucket ${outputs.webBucketName ?? ""}`,
];

writeFileSync("api/.env.local", api.join("\n") + "\n");
writeFileSync("web/.env.local", web.join("\n") + "\n");
console.log("wrote api/.env.local and web/.env.local. Start with: pnpm dev");
